# Generated by Django 3.0.2 on 2020-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpost',
            name='order_status',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (0, 0), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordertrn',
            name='order_status',
            field=models.CharField(choices=[(1, 1), (2, 2), (0, 0), ('CANCELLED', 'CANCELLED')], max_length=255),
        ),
        migrations.AlterField(
            model_name='verifylog',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
