# Generated by Django 3.0.2 on 2020-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200319_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpost',
            name='deleted_by',
            field=models.CharField(choices=[(1, 1), (2, 2), (0, 0), (-1, -1), ('CANCELLED', 'CANCELLED')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderpost',
            name='order_status',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (0, 0), (-1, -1), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordertrn',
            name='order_status',
            field=models.CharField(choices=[(1, 1), (2, 2), (0, 0), (-1, -1), ('CANCELLED', 'CANCELLED')], max_length=255),
        ),
    ]
