# Generated by Django 3.0.2 on 2020-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200323_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpost',
            name='deleted_by',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
