# Generated by Django 3.0.2 on 2020-03-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200323_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpost',
            old_name='deleted_by',
            new_name='buyer_status',
        ),
        migrations.AddField(
            model_name='orderpost',
            name='seller_status',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
