# Generated by Django 3.0.2 on 2020-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20200324_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpost',
            name='order_status',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (0, 0), (-1, -1), (-2, -2)], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordertrn',
            name='order_status',
            field=models.CharField(choices=[(1, 1), (2, 2), (0, 0), (-1, -1), (-2, -2)], max_length=255),
        ),
    ]
