# Generated by Django 3.0.2 on 2020-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20200330_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
