# Generated by Django 3.0.2 on 2020-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_notification_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
