# Generated by Django 3.0.2 on 2020-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20200413_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothstyle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
