# Generated by Django 3.0.2 on 2020-04-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_clothstyle_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothstylecolour',
            name='cloth_style',
        ),
        migrations.RemoveField(
            model_name='clothstylecolour',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='relpostclothstyle',
            name='cloth_style',
        ),
        migrations.RemoveField(
            model_name='relpostclothstyle',
            name='post',
        ),
        migrations.RemoveField(
            model_name='relpostclothstylecolour',
            name='cloth_style',
        ),
        migrations.RemoveField(
            model_name='relpostclothstylecolour',
            name='post',
        ),
        migrations.DeleteModel(
            name='ClothStyle',
        ),
        migrations.DeleteModel(
            name='ClothStyleColour',
        ),
        migrations.DeleteModel(
            name='RelPostClothStyle',
        ),
        migrations.DeleteModel(
            name='RelPostClothStyleColour',
        ),
    ]
