# Generated by Django 3.0.2 on 2020-04-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_clothstyle_clothstylecolour_clothstylecolourimage_relpostclothstyle_relpostclothstylecolour'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothstylecolour',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ClothStylePatternColourImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=255)),
                ('cloth_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.ClothStyle')),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.ClothStyleColour')),
                ('pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Pattern')),
            ],
            options={
                'verbose_name': 'clothstylepatterncolourimage',
                'verbose_name_plural': 'clothstylepatterncolourimages',
                'db_table': 'clothstylepatterncolourimage',
            },
        ),
    ]
