# Generated by Django 3.0.2 on 2020-04-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20200414_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relpostclothstylecolour',
            old_name='cloth_style',
            new_name='cloth_style_colour',
        ),
        migrations.RenameField(
            model_name='relpostpattern',
            old_name='cloth_style',
            new_name='pattern',
        ),
        migrations.RenameField(
            model_name='relpostsew',
            old_name='cloth_style',
            new_name='sew',
        ),
        migrations.RenameField(
            model_name='relpostshape',
            old_name='cloth_style',
            new_name='shape',
        ),
        migrations.RenameField(
            model_name='relpostshapecolour',
            old_name='cloth_style',
            new_name='shape_colour',
        ),
    ]
