# Generated by Django 3.0.2 on 2020-05-04 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_fabriccolour_fabriccolourimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'duepayment',
                'verbose_name_plural': 'duepayments',
                'db_table': 'duepayment',
            },
        ),
    ]
