# Generated by Django 3.0.2 on 2020-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_duepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
