# Generated by Django 3.0.2 on 2020-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_auto_20200602_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothstylecolour',
            old_name='image',
            new_name='front_image',
        ),
        migrations.RemoveField(
            model_name='clothstylepatterncolourimage',
            name='image',
        ),
        migrations.AddField(
            model_name='clothstylecolour',
            name='back_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clothstylepatterncolourimage',
            name='back_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clothstylepatterncolourimage',
            name='front_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
