# Generated by Django 3.0.2 on 2020-07-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_auto_20200630_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothstyle',
            name='back_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clothstyle',
            name='front_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
