# Generated by Django 3.0.2 on 2020-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20200701_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeFillColour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colour', models.CharField(default='', max_length=59)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'shapefillcolour',
                'verbose_name_plural': 'shapefillcolours',
                'db_table': 'shapefillcolour',
            },
        ),
    ]
