# Generated by Django 3.0.2 on 2020-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_shapefillcolour'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(default='', max_length=59)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'custsize',
                'verbose_name_plural': 'custsizes',
                'db_table': 'custsize',
            },
        ),
    ]
