# Generated by Django 3.0.2 on 2020-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_auto_20200721_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
