# Generated by Django 3.0.2 on 2020-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0029_auto_20200806_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
